config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do

  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'
  get 'help/online_job'     => 'help#online_job'
  get 'help/merge_request_check'     => 'help#merge_request_check'

  resource :build, controller: "build"

  resources :beta_deploy_logs, only: [:index] do
    put :vote, on: :member
    put :unvote, on: :member
  end

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:show]
    root to: "projects#index"
  end


  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]
    resource :ci_builds, controller: 'ci_builds', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      resources :members, only: [:destroy]
    end

    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create]
      resources :keys
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }
  match "/scripts/:id" => "scripts#show", constraints: { id: /\d+/ }
  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
      get :sonar
      get :grouping_strategies
      get :checkers
      get :artifacts
      get :swimlane
    end
  end

  resources :classifications, only: [:index] do

  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :databaseinfo
      get :issues
      get :merge_requests
      get :members
      get :tickets
      get :rollout_logs
      get :packages
      get :groups_for_package
      get :package_logs
      put :logs
      put :static_logs
    end
    resources :users_groups, only: [:create, :update, :destroy]
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  match "groups/logs", :to => "groups#logs"
  match "deploy_to_maven/deploy", :to => "deploy_to_maven#deploy"
  match "deploy_to_maven/pre_deploy", :to => "deploy_to_maven#pre_deploy"
  match "deploy_to_maven/deploy_status", :to => "deploy_to_maven#deploy_status"


  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /(?:[a-zA-Z.0-9_\-]+\/)?[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      get :packages_for_ticket
      get :rollback
      get :rollback_logs
      post :fork
      get :autocomplete_sources
      get :assignees
    end

    scope module: :projects do
      resources :blob,    only: [:show], constraints: {id: /.+/}
      resources :raw,    only: [:show], constraints: {id: /.+/}
      resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
      resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare, only: [:index, :create]
      resources :blame,   only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs, only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create] do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end
        member do
          get "history"
        end
      end

      resource :wall, only: [:show] do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive"
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, constraints: { id: /[a-zA-Z.0-9\/_\-#%+]+/ }, only: [:index, :new, :create, :destroy] do
        collection do
          get :recent
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy]
      resources :protected_branches, only: [:index, :create, :destroy]

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   /[a-zA-Z.0-9\/_\-#%+]+/,
              path: /.*/
            }
        end
      end


      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          get :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
          put :info_to_verify
          get :merge_inspect
        end
      end

      resources :hooks, only: [:index, :create, :destroy] do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy]

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :tasks do
        member do
          put :update_status
          post :remove_relation
        end
        resources :task_configs, path: 'configs'
      end

      resources :paas_rollouts do
        member do
          put :deploy
          put :reset
          get :log
        end
      end

      resources :beta_paas_rollouts do
        member do
          put :deploy
          put :reset
          get :tags
          put :rollback
        end

        collection do
          get :get_status_from_paas
          get :log
        end

      end

      resources :tickets do
        collection do
          get :current
        end

        member do
          put :wars
          put :add_wars
          get :grouping_strategy
          get :logs
        end
        resources :grouping_strategies, path: "strategies", only: [] do
          member do
            put :reset
            put :deploy_by_group
            put :terminate
            get :pre_rollback
            get :info_to_verify
            get :group_operation_logs
          end
        end
      end

      resources :online_jobs do
        collection do
          get :jars
          get :tags_for_jar
          get :ips_for_business
          get :business_groups
        end
        member do
          get :item

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :project, only: [:edit, :show, :update, :destroy, :team_update]

  def index
    owner_id = params[:owner_id]
    user = User.find_by_id(owner_id)

    @projects = user ? user.owned_projects : Project.scoped
    @projects = @projects.where(public: true) if params[:public_only].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page]).per(20)
  end

  def show
    @repository = @project.repository
    @group = @project.group
  end

  protected

  def project
    id = params[:project_id] || params[:id]

    @project = Project.find_with_namespace(id)
    @project || render_404
  end
end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_filter :project
  before_filter :repository
  layout 'projects'
end

app/controllers/projects/beta_paas_rollouts_controller.rb
class Projects::BetaPaasRolloutsController <  Projects::ApplicationController
  def deploy
    beta_paas_rollout = BetaPaasRollout.find(params[:id])
    status = beta_paas_rollout.deploy(beta_paas_rollout.paas_version) ? true : false
    render :json =>{status:status,notice:"the war has been sent to beta_paas to deploy..."} 
  end

  def log
    @beta_paas_rollout = BetaPaasRollout.find(params[:beta_paas_id])
    render partial: "projects/ci_branch/java/beta_paas_rollouts",locals:{paas_rollout: @beta_paas_rollout, logs: @beta_paas_rollout.build_branch.module_beta_last_logs(@beta_paas_rollout.appname) }
  end

  def rollback
    beta_paas_rollout = BetaPaasRollout.find(params[:beta_paas_rollout_id])
    result = beta_paas_rollout.deploy(params[:paas_version])
    render json: {result:result}
  end

  def tags
    beta_paas = BetaPaasRollout.find(params[:id])
    beta_logs = BetaPaasLog.where(:module_name =>beta_paas.appname,:build_branch_id => beta_paas.build_branch_id,:status =>200).uniq_by(&:tag)
    data = beta_logs.map{|log|{value:"#{log.tag}".split(//).first(20).join+"("+"#{log.created_at.strftime("%Y-%m-%d %H:%M:%S")}"+")",id:"#{log.tag}"}}
    render :json => data.uniq.to_json
  end

  def get_status_from_paas
    beta_paas_rollout = BetaPaasRollout.find(params[:beta_paas_rollout_id])
    imf = DianpingPaas::Client.new(url: Settings.op['beta_paas_url']).rollout_status(beta_paas_rollout.appname, beta_paas_rollout.operation_id)
    if imf['data']['operationStatus'].to_i != beta_paas_rollout.status
      beta_paas_rollout.mock_paas_callback(imf)
      if imf['data']["operationStatus"].to_i != 400  && imf['data']["operationStatus"].to_i != 200
        beta_paas_rollout.status = imf['data']["operationStatus"].to_i
      elsif imf['data']["operationStatus"].to_i == 200 && beta_paas_rollout.status != 200
        beta_paas_rollout.succeed
      end
      beta_paas_rollout.save
      beta_paas_rollout.reload_log_imf(imf)
    end
    render text: beta_paas_rollout.try(:status_message)
  end
    
end

app/controllers/projects/blame_controller.rb
# Controller for viewing a file's blame
class Projects::BlameController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)
    @blame = Gitlab::Git::Blame.new(project.repository, @commit.id, @path)
  end
end

app/controllers/projects/blob_controller.rb
# Controller for viewing a file's blame
class Projects::BlobController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)
  end
end

app/controllers/projects/branches_controller.rb
class Projects::BranchesController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :require_non_empty_project

  before_filter :authorize_code_access!
  before_filter :authorize_push!, only: [:create]
  before_filter :authorize_admin_project!, only: [:destroy]

  def index
    @branches = Kaminari.paginate_array(@repository.branches).page(params[:page]).per(30)
  end

  def recent
    @branches = @repository.recent_branches
  end

  def create
    @repository.add_branch(params[:branch_name], params[:ref])

    if new_branch = @repository.find_branch(params[:branch_name])
      Event.create_ref_event(@project, current_user, new_branch, 'add')
    end

    redirect_to project_branches_path(@project)
  end

  def destroy
    branch = @repository.find_branch(params[:id])

    if branch && @repository.rm_branch(branch.name)
      Event.create_ref_event(@project, current_user, branch, 'rm')
    end

    ci_branch_id = @project.ci_branchs.find_by_branch_name(params[:id]).try(:id)
    CiDestroyWorker.perform_async(ci_branch_id) unless ci_branch_id.blank?

    respond_to do |format|
      format.html { redirect_to project_branches_path(@project) }
      format.js { render nothing: true }
    end
  end
end

app/controllers/projects/caches_controller.rb
class Projects::CachesController < Projects::ApplicationController
  def show
    @rollout = @project.rollout_branch
  end

  def clear
    @rollout = @project.rollout_branch
    @status = @rollout.clear_ip_cache(params[:ip], params[:type])
    render :json => @status
  end  
end

app/controllers/projects/commit_controller.rb
# Controller for a specific Commit
#
# Not to be confused with CommitsController, plural.
class Projects::CommitController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    result = CommitLoadContext.new(project, current_user, params).execute

    @commit = result[:commit]

    if @commit.nil?
      git_not_found!
      return
    end

    @suppress_diff = result[:suppress_diff]

    @note        = result[:note]
    @line_notes  = result[:line_notes]
    @notes_count = result[:notes_count]
    @target_type = :commit
    @target_id   = @commit.id

    @comments_allowed = @reply_allowed = true
    @comments_target  = { noteable_type: 'Commit',
                          commit_id: @commit.id }

    respond_to do |format|
      format.html do
        if result[:status] == :huge_commit
          render "huge_commit" and return
        end
      end

      format.diff  { render text: @commit.to_diff }
      format.patch { render text: @commit.to_patch }
    end
  end
end

app/controllers/projects/commits_controller.rb
require "base64"

class Projects::CommitsController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @repo = @project.repository
    @limit, @offset = (params[:limit] || 40), (params[:offset] || 0)

    @commits = @repo.commits(@ref, @path, @limit, @offset)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom { render layout: false }
    end
  end
end

app/views/projects/tickets/_clear_filter.html.haml
%fieldset
  - if ["status", "scope", "released_at", extra].select { |k| params[k].present? }.any?
    = link_to list_tickets_path, class: 'cgray pull-right' do
      %i.icon-remove
      %strong Clear filter

app/views/projects/tickets/_configs.html.haml
- if ticket_task_packages(@ticket) && !@ticket.package_tasks.blank?
  %div#lion-config-table
    %table
      %tr
        %th 应用名称
        %th Key名称
        %th 上线Value
        %th 操作
        %th 状态

      %tbody
      - @ticket.package_tasks.each do |task|
        - if !task.configs.blank?
          - task.configs.each do |config|
            %tr 
              %td  #{config.name}
              %td  #{config.key}
              %td  #{config.online_value}
              %td  #{config.online_op}
              %td  #{config.status}
- else
  %h5
    本上线发布没有配置信息...

app/views/projects/tickets/_grouping_strategy.html.haml
- gss = gss || nil
- error = error || nil
- tag = module_last_tag(package.id)
- prs = prs || nil
%legend= "分组操作(#{package.try(:name)}#{tag})"
-if !gss.blank? || !prs.blank?
  %table{ class: "grouping-strategies-list", "data-package-id" => package.id }
    %thead
      %tr
        %th GroupName
        %th SwimLane
        %th Status
        %th Action
        %th Detail

    %tbody
    -if !gss.blank?
      - gss.each do |gs|
        - prompt = collect_tips(gs)
        %tr{ class: "grouping-item-info", "data-group-id" => gs.id }
          %td
            %a.group-hostname{ :"data-content" => gs.hostname,:title=>"",
                              :"data-placement" => 'top',
                              :"data-trigger" => 'hover' } #{gs.name}
          %td #{gs.swimlane}
          - if gs.in_progress?
            %td
              %i.icon-spinner.icon-spin.icon-large{style: "color: red"}
              #{gs.status_name.to_s.titleize}
          - else
            - if gs.status_name.to_s.include?("success")
              %td{style:"color:#1A1"} #{gs.status_name.to_s.titleize}
            - elsif gs.status_name.to_s.include?("fail")
              %td{style:"color:red"} #{gs.status_name.to_s.titleize}
            - else
              %td #{gs.status_name.to_s.titleize}
          %td
            .btn-group
              - if !gs.ready_deploy? && gs.can_deploy?
                %button.btn{ title: "发布", class: "grouping-strategy-operation-tips btn-primary", "data-content" => "#{prompt}" }
                  %div{class:"grouping-strategy-operation-tips-content",style: "display:none"}
                    = prompt
                  发布
              - if gs.ready_deploy? && gs.can_deploy?                
                - if gs.display_confirm_or_not_when_deploy?
                  %button.btn{check_deploy(gs.id)}
                    发布
                - else
                  %button.btn{ title: "发布", class: "info_to_verify btn-primary", "data-link" =>info_to_verify_project_ticket_grouping_strategy_path(@project, ticket, gs,{package_id: package.id}) }
                    发布
              - if gs.can_kill?
                %button.btn{ title: "terminate", class: "release-terminate release-btn btn-danger", "data-link" => terminate_project_ticket_grouping_strategy_path(@project, ticket, gs)}
                  中止
              - if gs.can_rollback?
                = link_to pre_rollback_project_ticket_grouping_strategy_path(@project, ticket,gs,{package_id: package.id}), title:"点击进入回滚页面", method: :pre_rollback,target: "_blank",method: "get",class: "btn btn-rollback btn-danger" do
                  回滚
              - if gs.can_reset?
                %button.btn{ title: "reset", class: "release-reset ", "data-link" => reset_project_ticket_grouping_strategy_path(@project, ticket, gs) }
                  重置
            - if !prompt.nil? && !gs.can_do?
              %i.icon-question-sign{ class: "grouping-strategy-operation-tips",title: "提示","data-content" => "#{prompt}"}
                %div{class:"grouping-strategy-operation-tips-content",style: "display:none"}
                  = prompt

          %td
            - unless gs.log.nil?
              = link_to gs.log, :target => "_blank",:title=>"点击查看发布详情" do
                %i.icon-film
            - else
              %i.icon-film{ style: 'color:grey', :target => "_blank", :title=>'暂无详情'}
    - if !prs.blank?
      = render partial: "projects/paas_rollouts/rollout", locals: { prs: prs } if prs.present?
      
  %td
    %button.btn.hide_grouping_strategy{:onclick =>"$('.ticket-packing-item').replaceWith('<div class="'"span6 ticket-packing-item"'"><legend> 分组操作</legend><h4>点击左边的War包,进行上线操作...</h4></div>')"}
      %i.icon-remove
        隐藏      
   
- elsif error.blank?
  %h4
    %i.icon-warning-sign{style:""}
      很抱歉，指定package没有分组信息...
    %br
    - if cmdb_info_exist && package.has_paas? && prs.blank?
      %i.icon-warning-sign
        Can't conntect paas server or paas has no groups of package!
    - else    
      %i.icon-warning-sign
        还木有机器,
        %a{href:"http://workflow.dp/wfe/start/77",style:"color:red"}请点我进行线上机器和分组申请
- else
  %h4
    %i.icon-warning-sign
    = error    



#workflow.modal.hide.fade
  .modal-header
    %a.close{ "data-dismiss" => "modal" } ×
    %h4{ style: "color:red" } 上线单未完成，不能上线
  .modal-body
    %div#unfinished_workflow_items

app/views/projects/tickets/_item.html.haml
%h5 Click wars in left table to show  detail of grouping strategy.

app/views/projects/tickets/_task_package.html.haml
%tr{"data-link" => grouping_strategy_project_ticket_path(@project, @ticket, package) }
  %td  #{package.id}
  %td  #{package.name}
  %td
    = select_tag "Tag", module_tag_collections(package.name), class: "project-refs-select chosen"
  %td  
    = link_to task.project.name, project_path(@project)
  %td  #{task.released_at}

app/views/projects/tickets/_tasks.html.haml
- if !@ticket.package_tasks.blank?
  %div
    %table
      %tr
        %th Subject
        %th Description
        %th Assignee
        %th Creator
        %th Released_at
        %th Action

      %tbody
      - @ticket.package_tasks.each do |task|
        %tr 
          %td
            = link_to task.subject, project_task_path(task.project,task)
          %td  #{task.description}
          %td  #{task.assignee.name}
          %td  #{task.creator.name}
          %td  #{task.released_at}
          %td
            = hidden_field_tag :ticket_id, @ticket.id
            = link_to remove_relation_project_task_path(@project, task), class: "btn btn-danger", method: "remove_relation",confirm: "Are you sure to remove relation from this ticket?" do
              %i.icon-remove
              删除
- else
  %h5
    本上线发布没有相关的开发任务...

app/views/projects/tickets/_ticket.html.haml
%li.ticket{class: cycle("odd", "even")}
  .ticket-subject.clearfix
    = link_to project_ticket_path(project, ticket), class: "row_title" do
      = "Rollout Ticket ##{ticket.id}"
      %small.cgray release at
      = "#{ticket.released_at.stamp("2011-08-21")}"
    - unless @project
      %small.cgray belongs to
      = link_to ticket.project.name_with_namespace, project_path(ticket.project)
    %small.pull-right
      = ticket.status_name.to_s.titleize
  .ticket-info.clearfix
    .pull-right
      Last update at #{ticket.updated_at.stamp("2011-08-21")}

    Tasks
    %span.badge.badge-info= ticket.package_tasks.count
    Configs
    %span.badge.badge-info= ticket.configs.count
    

app/views/projects/tickets/_ticket_filter.html.haml
%fieldset
  %ul.nav.nav-pills.nav-stacked
    %li{class: ("active" if params[:scope].blank?)}
      = link_to tickets_filter_path(scope: nil) do
        Today
    %li{class: ("active" if params[:scope] == "all")}
      = link_to tickets_filter_path(scope: 'all') do
        All
    %li{class: ("active" if params[:scope] == "since-today")}
      = link_to tickets_filter_path(scope: "since-today") do
        Since Today
    %li{class: ("active" if params[:scope] == 'tomorrow')}
      = link_to tickets_filter_path(scope: 'tomorrow') do
        Tomorrow

  %ul.nav.nav-pills.nav-stacked
    %li{class: ("active" if params[:status].blank?)}
      = link_to tickets_filter_path(status: nil) do
        All
    - Ticket.state_machines[:status].states.each do |state|
      %li{class: ("active" if params[:status].to_i == state.value)}
        = link_to tickets_filter_path(status: state.value) do
          = state.name.to_s.titleize

app/views/projects/tickets/_wars.html.haml
.span6
  %legend= "包信息(选择一个包进行操作)"
  %table#ticket-packing-list{class: "packages_info"}
    %thead
      %tr
        %th WarName
        %th Tag
        %th CreatedBy
    - if @packages.present?
      - @packages.each do |package|
        = render "ticket_package", package: package, ticket: @ticket
  - if @project.ticket_add_wars_enabled && (@project.rollout_branch.blank? || @project.rollout_branch.java?)
    %td
      = link_to wars_project_ticket_path(@project, @ticket), class: "btn btn-new", method: :put do
        %i.icon-edit
        增加War包

.span6
  .loading.hide
  .ticket-packing-item
    %legend= "分组操作"
    - if @project.rollout_branch.java?
      %h4 点击左边的 War 包,进行上线操作...
    - else
      %h4 点击左边的 Zip 包,进行上线操作...

app/views/projects/tickets/edit.html.haml
= render "projects/rollout_branches/head"

%div
  %h3.page-title
    Edit Rollout Ticket
  %hr
    = render "form"

app/views/projects/tickets/index.html.haml
= render "projects/rollout_branches/head"

%h3.page-title
  Rollout Tickets
  %span="(#{@tickets.size})"

.row
  .span3
    = render 'ticket_filter'
    = render 'clear_filter', extra: nil
  .span9
    .ui-box
      =render "head_filter"
      %ul.well-list.ticket-list
        - @tickets.each do |ticket|
          = render partial: "ticket", locals: {ticket: ticket, project: @project}
        - if @tickets.blank?
          %li
            %h4.nothing_here_message No tickets to show
    - if @tickets.present?
      .pull-right
        %span.cgray.pull-right #{@tickets.total_count} rollout tickets for this filter

      = paginate @tickets, theme: "gitlab"

app/views/projects/tickets/show.html.haml
= render "projects/rollout_branches/head"

%h3.page-title
  = "Ticket ##{@ticket.id} #{@ticket.released_at} :"

.box-title.clearfix
  .back-link
    .btn-group
      = link_to project_tickets_path(@project), class: "btn" do
        %i.icon-long-arrow-left
        To Rollout Tickets
    .pull-right
      自动刷新状态:
      .make-switch.switch-small.auto-refresh{ 'data-on' => "info" }
        %input.auto-refresh-box{ type: "checkbox", checked: true }

  .row
    %div{style: "margin:0;padding:0;display:inline"}
      %h5.box-title
        = render "wars"
  %br

  %legend= "配置信息"
  %div{style: "margin:0;padding:0;display:inline"}
    %h5.box-title.clearfix
      = render "configs"
      %br

  %legend= "开发任务"
  %div{style: "margin:0;padding:0;display:inline"}
    %h5.box-title.clearfix
      = render "tasks"

= render 'projects/grouping_strategies/deploy_check'

#confirmModal.modal.large.hide.fade